require('./connection/db')
const express=require('express')
const cors=require('cors')

const route=require('./route/route')
const app=express()
app.use(cors())
app.use(express.json())
app.use(express.urlencoded())
app.use('/',route)
app.listen(4000,()=>console.log('server connected'))